# Generated by Django 5.2.8 on 2025-11-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='qr',
            field=models.CharField(max_length=1000),
        ),
    ]
