# Generated by Django 5.2.8 on 2025-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_submission_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='fingerprint_binary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
