# Generated by Django 5.2.8 on 2025-11-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_submission_fingerprint_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='fingerprint_binary',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='fingerprint_taken',
        ),
    ]
