# Generated by Django 5.2.8 on 2025-11-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_remove_submission_fingerprint_binary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='registered_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
