# Generated by Django 5.2.8 on 2025-12-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_submission_registered_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
